### ISSUE TITLE
Skin name: Neo Pax Jax CRASH

### ISSUE THREAD

**Issue by WGPL777** [koobzaar/lol-skins#215]
## Description
Game crashes each time when trying to enter game with neo pax jax skin injected

**Comment by koobzaar** [comment]
Should be fixed.

**Comment by darpanarora82** [comment]
this issue is still there. whenever match loads up, can't see the screen and always stuck on reconnect. When clicked on reconnect, it just crashes back to reconnected screen again. Have you tried with the latest patch version of league?

PS: Thanks for all the efforts you're putting in. You are SIR, A Legend!
